default: &default
  adapter: postgresql
  pool: 10
  timeout: 5000
  host: localhost
  encoding: unicode
  username: postgres
  password: postgres

development:
  <<: *default
  database: bot_development

test:
  <<: *default
  database: bot_test

production:
  <<: *default
  database: bot